import shelve
import random

# Lista ampliada de palabras reales en español (4-8 caracteres)
PALABRAS_BASE = [
    'sol', 'luna', 'casa', 'arbol', 'rio', 'cielo', 'mar', 'flor', 'camino', 'puerta',
    'libro', 'mesa', 'silla', 'ventana', 'jardin', 'python', 'codigo', 'programa', 'estrella', 'nube',
    'puente', 'bosque', 'lago', 'ciudad', 'playa', 'campo', 'luz', 'rioja', 'valle', 'colina',
    'piedra', 'arena', 'viento', 'fuego', 'aire', 'tierra', 'nieve', 'lluvia', 'arroyo', 'prado',
    'selva', 'montaña', 'roca', 'hoja', 'rama', 'noche', 'dia', 'ruta', 'calle', 'plaza',
    'sendero', 'avenida', 'parque', 'cueva', 'ola', 'gema', 'cristal', 'metal', 'oro', 'plata',
    'cobre', 'hierro', 'acero', 'madera', 'leña', 'fruta', 'semilla', 'raiz', 'tallo', 'planta',
    'arbusto', 'cesped', 'tormenta', 'trueno', 'rayo', 'ceniza', 'humo', 'barro', 'polvo',
    'alba', 'ocaso', 'brisa', 'huracán', 'niebla', 'rocio', 'granizo', 'ladera', 'cumbre', 'barranco',
    'desierto', 'oasis', 'pantano', 'laguna', 'arrecife', 'coral', 'espuma', 'orilla', 'marea',
    'acantilado', 'península', 'isla', 'volcán', 'cráter', 'lava', 'glaciar', 'iceberg', 'tundra',
    'estepa', 'sabana', 'pradera', 'humedal', 'manglar', 'alamo', 'roble', 'pino', 'cedro', 'abeto',
    'sauce', 'olmo', 'haya', 'castaño', 'nuez', 'almendra', 'avellana', 'pistacho', 'manzana', 'pera',
    'uva', 'higo', 'ciruela', 'melocotón', 'albaricoque', 'cereza', 'fresa', 'frambuesa', 'mora',
    'arandano', 'kiwi', 'mango', 'papaya', 'piña', 'coco', 'banana', 'limon', 'naranja', 'mandarina',
    'pomelo', 'granada', 'caqui', 'membrillo', 'guayaba', 'maracuya', 'lichi', 'durazno', 'nectarina',
    'melón', 'sandía', 'calabaza', 'pepino', 'tomate', 'pimiento', 'berza', 'col', 'lechuga',
    'espinaca', 'acelga', 'rúcula', 'apio', 'zanahoria', 'remolacha', 'nabo', 'rábano', 'cebolla',
    'ajo', 'puerro', 'esparrago', 'alcachofa', 'brócoli', 'coliflor', 'maíz', 'trigo', 'avena',
    'cebada', 'arroz', 'lenteja', 'garbanzo', 'frijol', 'soja', 'guisante', 'haba', 'cacahuete',
    'sésamo', 'girasol', 'amapola', 'rosa', 'lirio', 'tulipán', 'margarita', 'clavel', 'orquídea',
    'jazmín', 'azucena', 'narciso', 'violeta', 'lavanda', 'romero', 'tomillo', 'albahaca', 'perejil',
    'cilantro', 'menta', 'orégano', 'laurel', 'salvia', 'estragón', 'eneldo', 'comino', 'canela',
    'clavo', 'jengibre', 'cúrcuma', 'azafrán', 'pimienta', 'vainilla', 'cardamomo', 'anís', 'hinojo',
    'mostaza', 'río', 'lago', 'mar', 'océano', 'playa', 'duna', 'costa', 'bahía', 'golfo', 'estrecho',
    'canal', 'rápido', 'cascada', 'manantial', 'pozo', 'fuente', 'arroyo', 'torrente', 'glaciar',
    'fiordo', 'delta', 'meandro', 'cañón', 'meseta', 'llanura', 'colina', 'cerro', 'montaña', 'sierra',
    'cordillera', 'volcán', 'cráter', 'ladera', 'cumbre', 'valle', 'barranco', 'desierto', 'oasis',
    'pantano', 'humedal', 'manglar', 'bosque', 'selva', 'jungla', 'pradera', 'estepa', 'sabana',
    'tundra', 'taiga', 'ciénaga', 'laguna', 'arrecife', 'coral', 'orilla', 'marea', 'acantilado',
    'península', 'isla', 'atolón', 'archipiélago', 'cueva', 'gruta', 'caverna', 'roca', 'piedra',
    'guijarro', 'arena', 'grava', 'arcilla', 'barro', 'lodo', 'polvo', 'ceniza', 'humo', 'vapor',
    'niebla', 'rocio', 'nube', 'lluvia', 'nieve', 'granizo', 'tormenta', 'huracán', 'tornado',
    'brisa', 'viento', 'ráfaga', 'tempestad', 'trueno', 'rayo', 'relámpago', 'luz', 'sombra',
    'alba', 'amanecer', 'ocaso', 'crepúsculo', 'noche', 'día', 'sol', 'luna', 'estrella', 'planeta',
    'cometa', 'meteorito', 'galaxia', 'cielo', 'nube', 'aurora', 'arcoíris', 'eclipse', 'órbita',
    'satélite', 'constelación', 'firmamento', 'casa', 'hogar', 'vivienda', 'edificio', 'cabaña',
    'choza', 'mansión', 'palacio', 'castillo', 'torre', 'muralla', 'puerta', 'ventana', 'tejado',
    'techo', 'suelo', 'piso', 'pared', 'chimenea', 'hogar', 'sala', 'comedor', 'cocina', 'dormitorio',
    'baño', 'ático', 'sótano', 'garaje', 'jardín', 'patio', 'terraza', 'balcón', 'escalera',
    'pasillo', 'corredor', 'mueble', 'mesa', 'silla', 'sofá', 'cama', 'armario', 'estante', 'librero',
    'escritorio', 'lámpara', 'alfombra', 'cortina', 'persiana', 'espejo', 'cuadro', 'reloj', 'vela',
    'candil', 'foco', 'bombilla', 'ventilador', 'calefactor', 'radiador', 'estufa', 'horno', 'microondas',
    'nevera', 'congelador', 'lavadora', 'secadora', 'lavavajillas', 'tostadora', 'batidora', 'cafetera',
    'ollas', 'sartén', 'cuchillo', 'tenedor', 'cuchara', 'plato', 'vaso', 'taza', 'jarra', 'botella',
    'copa', 'bandeja', 'mantel', 'servilleta', 'cubiertos', 'cocina', 'receta', 'ingrediente', 'sabor',
    'aroma', 'especia', 'sal', 'azúcar', 'miel', 'sirope', 'aceite', 'vinagre', 'salsa', 'caldo',
    'sopa', 'ensalada', 'carne', 'pollo', 'cerdo', 'ternera', 'cordero', 'pescado', 'marisco', 'gamba',
    'cangrejo', 'langosta', 'mejillón', 'almeja', 'ostra', 'calamar', 'pulpo', 'atún', 'salmón',
    'trucha', 'merluza', 'bacalao', 'sardina', 'anchoa', 'arenque', 'langostino', 'camarón', 'cangrejo',
    'bogavante', 'rape', 'lubina', 'dorada', 'pez', 'tiburón', 'ballena', 'delfín', 'foca', 'morsa',
    'pingüino', 'gaviota', 'albatros', 'pelícano', 'cormorán', 'garza', 'cigüeña', 'flamenco', 'cisne',
    'pato', 'ganso', 'águila', 'halcón', 'buitre', 'búho', 'lechuza', 'cuervo', 'gorrión', 'paloma',
    'cotorra', 'loro', 'periquito', 'canario', 'jilguero', 'ruiseñor', 'mirlo', 'estornino', 'golondrina',
    'avestruz', 'emu', 'ñandú', 'kiwi', 'pavo', 'gallina', 'gallo', 'pollito', 'codorniz', 'perdiz',
    'faisán', 'tórtola', 'colibrí', 'tucán', 'pájaro', 'ave', 'pluma', 'ala', 'pico', 'garra',
    'nido', 'huevo', 'reptil', 'serpiente', 'víbora', 'cobra', 'pitón', 'boa', 'lagarto', 'iguana',
    'camaleón', 'gecko', 'dragón', 'tortuga', 'galápago', 'cocodrilo', 'caimán', 'anfibio', 'rana',
    'sapo', 'salamandra', 'tritón', 'insecto', 'mosca', 'mosquito', 'abeja', 'avispa', 'hormiga',
    'termita', 'cucaracha', 'grillo', 'saltamontes', 'langosta', 'mariquita', 'escarabajo', 'mariposa',
    'polilla', 'libélula', 'araña', 'escorpión', 'ciempiés', 'milpiés', 'gusano', 'oruga', 'caracol',
    'babosa', 'lombriz', 'sanguijuela', 'medusa', 'anémona', 'coral', 'esponja', 'estrella', 'erizo',
    'pepino', 'molusco', 'calamar', 'pulpo', 'almeja', 'ostra', 'mejillón', 'caracol', 'babosa',
    'mamífero', 'elefante', 'rinoceronte', 'hipopótamo', 'jirafa', 'cebra', 'león', 'tigre', 'leopardo',
    'guepardo', 'pantera', 'lobo', 'zorro', 'perro', 'gato', 'oso', 'panda', 'koala', 'canguro',
    'wallaby', 'wombat', 'ornitorrinco', 'equidna', 'mono', 'gorila', 'chimpancé', 'orangután', 'babuino',
    'mandril', 'mico', 'lemur', 'murciélago', 'vampiro', 'ratón', 'rata', 'ardilla', 'castor', 'nutria',
    'comadreja', 'hurón', 'tejón', 'mapache', 'ciervo', 'alce', 'reno', 'gacela', 'antílope', 'búfalo',
    'bisonte', 'vaca', 'toro', 'oveja', 'cabra', 'cerdo', 'jabalí', 'caballo', 'burro', 'mula',
    'camello', 'dromedario', 'llama', 'alpaca', 'guanaco', 'vicuña', 'delfín', 'ballena', 'orca',
    'narval', 'cachalote', 'foca', 'morsa', 'manatí', 'dugongo', 'castor', 'nutria', 'tejón', 'mapache',
    'armadillo', 'oso', 'perezoso', 'tamandúa', 'hormiguero', 'erizo', 'topo', 'musaraña', 'conejo',
    'liebre', 'pica', 'marmota', 'hámster', 'gerbo', 'rata', 'ratón', 'ardilla', 'castor', 'nutria',
    'ciervo', 'alce', 'reno', 'gacela', 'antílope', 'búfalo', 'bisonte', 'vaca', 'toro', 'oveja',
    'cabra', 'cerdo', 'jabalí', 'caballo', 'burro', 'mula', 'camello', 'dromedario', 'llama', 'alpaca',
    'guanaco', 'vicuña', 'maestro', 'alumno', 'escuela', 'clase', 'lección', 'tarea', 'examen', 'nota',
    'profesor', 'estudio', 'libreta', 'lápiz', 'bolígrafo', 'papel', 'tinta', 'pizarra', 'tiza',
    'cuaderno', 'libro', 'lectura', 'escritura', 'dibujo', 'pintura', 'arte', 'música', 'canto',
    'guitarra', 'piano', 'violín', 'flauta', 'tambor', 'saxofón', 'trompeta', 'teclado', 'melodía',
    'ritmo', 'canción', 'poema', 'verso', 'rimas', 'historia', 'cuento', 'novela', 'teatro', 'drama',
    'comedia', 'escena', 'actor', 'actriz', 'director', 'escenario', 'público', 'aplauso', 'telón',
    'cine', 'película', 'pantalla', 'proyector', 'cámara', 'grabación', 'video', 'foto', 'imagen',
    'lente', 'foco', 'flash', 'álbum', 'retrato', 'paisaje', 'cuadro', 'marco', 'pincel', 'lienzo',
    'color', 'tinta', 'pigmento', 'paleta', 'diseño', 'moda', 'ropa', 'camisa', 'pantalón', 'vestido',
    'falda', 'chaqueta', 'abrigo', 'bufanda', 'sombrero', 'guante', 'zapato', 'bota', 'sandalia',
    'cinturón', 'bolso', 'mochila', 'maleta', 'viaje', 'avión', 'tren', 'autobús', 'coche', 'bicicleta',
    'moto', 'barco', 'velero', 'nave', 'cohete', 'espacio', 'planeta', 'satélite', 'astronauta', 'órbita',
    'luna', 'estrella', 'galaxia', 'cometa', 'meteorito', 'cielo', 'nube', 'sol', 'clima', 'tiempo',
    'lluvia', 'nieve', 'viento', 'tormenta', 'trueno', 'rayo', 'relámpago', 'niebla', 'rocio', 'hielo',
    'calor', 'frío', 'temperatura', 'estación', 'primavera', 'verano', 'otoño', 'invierno', 'día',
    'noche', 'amanecer', 'atardecer', 'alba', 'ocaso', 'crepúsculo', 'sombras', 'luz', 'oscuridad',
    'ciudad', 'pueblo', 'aldea', 'calle', 'avenida', 'plaza', 'parque', 'jardín', 'mercado', 'tienda',
    'compra', 'venta', 'dinero', 'moneda', 'billete', 'banco', 'cuenta', 'ahorro', 'préstamo', 'deuda',
    'pago', 'factura', 'recibo', 'precio', 'valor', 'costo', 'ganancia', 'pérdida', 'comercio', 'negocio',
    'empresa', 'oficina', 'trabajo', 'empleo', 'jefe', 'compañero', 'equipo', 'proyecto', 'tarea',
    'reunión', 'plan', 'estrategia', 'meta', 'objetivo', 'éxito', 'fracaso', 'esfuerzo', 'dedicación',
    'talento', 'habilidad', 'conocimiento', 'sabiduría', 'mente', 'cerebro', 'idea', 'pensamiento',
    'memoria', 'recuerdo', 'sueño', 'imaginación', 'creatividad', 'arte', 'ciencia', 'tecnología',
    'máquina', 'computadora', 'teléfono', 'internet', 'red', 'web', 'correo', 'mensaje', 'chat',
    'llamada', 'señal', 'onda', 'radio', 'televisión', 'pantalla', 'monitor', 'teclado', 'ratón',
    'software', 'programa', 'aplicación', 'sistema', 'archivo', 'carpeta', 'dato', 'información',
    'base', 'código', 'algoritmo', 'servidor', 'cliente', 'nube', 'almacenamiento', 'memoria', 'disco',
    'procesador', 'chip', 'circuito', 'cable', 'enchufe', 'batería', 'energía', 'electricidad',
    'voltaje', 'corriente', 'luz', 'lámpara', 'bombilla', 'foco', 'vela', 'linterna', 'fuego',
    'llama', 'ceniza', 'humo', 'calor', 'frío', 'hielo', 'vapor', 'gas', 'líquido', 'sólido',
    'materia', 'átomo', 'molécula', 'química', 'física', 'biología', 'ciencia', 'experimento',
    'laboratorio', 'investigación', 'descubrimiento', 'invento', 'patente', 'máquina', 'herramienta',
    'martillo', 'destornillador', 'llave', 'tornillo', 'clavo', 'sierra', 'taladro', 'pala', 'pico',
    'carretilla', 'construcción', 'edificio', 'casa', 'puente', 'carretera', 'túnel', 'torre',
    'muralla', 'cemento', 'ladrillo', 'teja', 'pintura', 'decoración', 'mueble', 'silla', 'mesa',
    'cama', 'sofá', 'armario', 'estante', 'escritorio', 'lámpara', 'alfombra', 'cortina', 'persiana',
    'espejo', 'cuadro', 'reloj', 'vela', 'candil', 'foco', 'bombilla', 'ventilador', 'calefactor',
    'radiador', 'estufa', 'horno', 'microondas', 'nevera', 'congelador', 'lavadora', 'secadora',
    'lavavajillas', 'tostadora', 'batidora', 'cafetera', 'ollas', 'sartén', 'cuchillo', 'tenedor',
    'cuchara', 'plato', 'vaso', 'taza', 'jarra', 'botella', 'copa', 'bandeja', 'mantel', 'servilleta',
    'cubiertos', 'cocina', 'receta', 'ingrediente', 'sabor', 'aroma', 'especia', 'sal', 'azúcar',
    'miel', 'sirope', 'aceite', 'vinagre', 'salsa', 'caldo', 'sopa', 'ensalada', 'carne', 'pollo',
    'cerdo', 'ternera', 'cordero', 'pescado', 'marisco', 'gamba', 'cangrejo', 'langosta', 'mejillón',
    'almeja', 'ostra', 'calamar', 'pulpo', 'atún', 'salmón', 'trucha', 'merluza', 'bacalao', 'sardina',
    'anchoa', 'arenque', 'langostino', 'camarón', 'cangrejo', 'bogavante', 'rape', 'lubina', 'dorada',
    'juego', 'deporte', 'fútbol', 'baloncesto', 'tenis', 'natación', 'ciclismo', 'atletismo', 'carrera',
    'salto', 'lanzamiento', 'gimnasia', 'yoga', 'boxeo', 'lucha', 'esgrima', 'karate', 'judo',
    'taekwondo', 'equipo', 'jugador', 'entrenador', 'árbitro', 'campo', 'cancha', 'estadio', 'pelota',
    'raqueta', 'red', 'portería', 'gol', 'punto', 'victoria', 'derrota', 'competencia', 'torneo',
    'medalla', 'trofeo', 'premio', 'honor', 'gloria', 'esfuerzo', 'disciplina', 'entrenamiento',
    'salud', 'cuerpo', 'mente', 'alma', 'corazón', 'sangre', 'hueso', 'músculo', 'piel', 'cabello',
    'vista', 'oído', 'olfato', 'gusto', 'tacto', 'sentido', 'emoción', 'alegría', 'tristeza', 'miedo',
    'enojo', 'amor', 'odio', 'paz', 'guerra', 'libertad', 'justicia', 'ley', 'regla', 'norma',
    'derecho', 'deber', 'responsabilidad', 'compromiso', 'promesa', 'juramento', 'verdad', 'mentira',
    'secreto', 'misterio', 'enigma', 'pista', 'solución', 'respuesta', 'pregunta', 'duda', 'curiosidad',
    'saber', 'conocimiento', 'sabiduría', 'inteligencia', 'genio', 'talento', 'habilidad', 'destreza',
    'arte', 'ciencia', 'tecnología', 'futuro', 'pasado', 'presente', 'tiempo', 'hora', 'minuto',
    'segundo', 'día', 'semana', 'mes', 'año', 'siglo', 'mileno', 'era', 'época', 'historia',
    'cultura', 'tradición', 'costumbre', 'fiesta', 'celebración', 'navidad', 'pascua', 'carnaval',
    'boda', 'cumpleaños', 'aniversario', 'regalo', 'sorpresa', 'alegría', 'felicidad', 'sonrisa',
    'risa', 'lágrima', 'dolor', 'sufrimiento', 'cura', 'medicina', 'salud', 'enfermedad', 'hospital',
    'doctor', 'enfermera', 'paciente', 'cirugía', 'tratamiento', 'terapia', 'farmacia', 'pastilla',
    'jarabe', 'inyección', 'vacuna', 'virus', 'bacteria', 'infección', 'fiebre', 'tos', 'dolor',
    'cabeza', 'estómago', 'corazón', 'pulmón', 'hígado', 'riñón', 'sangre', 'hueso', 'músculo',
    'piel', 'herida', 'cicatriz', 'vendaje', 'yeso', 'muletas', 'silla', 'cama', 'descanso', 'sueño',
    'reposo', 'energía', 'fuerza', 'debilidad', 'fatiga', 'cansancio', 'relajación', 'meditación',
    'yoga', 'ejercicio', 'caminata', 'carrera', 'natación', 'bicicleta', 'deporte', 'juego', 'diversión',
    'ocio', 'pasatiempo', 'lectura', 'escritura', 'dibujo', 'pintura', 'música', 'cine', 'teatro',
    'baile', 'danza', 'fiesta', 'reunión', 'amigo', 'familia', 'padre', 'madre', 'hijo', 'hija',
    'hermano', 'hermana', 'abuelo', 'abuela', 'tío', 'tía', 'primo', 'prima', 'sobrino', 'sobrina',
    'esposo', 'esposa', 'novio', 'novia', 'amor', 'boda', 'matrimonio', 'anillo', 'compromiso',
    'cita', 'encuentro', 'beso', 'abrazo', 'caricia', 'afecto', 'ternura', 'pasión', 'romance',
    'poema', 'carta', 'mensaje', 'regalo', 'flor', 'rosa', 'lirio', 'tulipán', 'margarita', 'clavel',
    'orquídea', 'jazmín', 'azucena', 'narciso', 'violeta', 'lavanda', 'romero', 'tomillo', 'albahaca',
    'perejil', 'cilantro', 'menta', 'orégano', 'laurel', 'salvia', 'estragón', 'eneldo', 'comino',
    'canela', 'clavo', 'jengibre', 'cúrcuma', 'azafrán', 'pimienta', 'vainilla', 'cardamomo', 'anís',
    'hinojo', 'mostaza', 'sabor', 'aroma', 'cocina', 'receta', 'ingrediente', 'plato', 'comida',
    'cena', 'almuerzo', 'desayuno', 'postre', 'tarta', 'pastel', 'helado', 'flan', 'pudín', 'fruta',
    'manzana', 'pera', 'uva', 'higo', 'ciruela', 'melocotón', 'albaricoque', 'cereza', 'fresa',
    'frambuesa', 'mora', 'arandano', 'kiwi', 'mango', 'papaya', 'piña', 'coco', 'banana', 'limon',
    'naranja', 'mandarina', 'pomelo', 'granada', 'caqui', 'membrillo', 'guayaba', 'maracuya', 'lichi',
    'durazno', 'nectarina', 'melón', 'sandía', 'calabaza', 'pepino', 'tomate', 'pimiento', 'berza',
    'col', 'lechuga', 'espinaca', 'acelga', 'rúcula', 'apio', 'zanahoria', 'remolacha', 'nabo',
    'rábano', 'cebolla', 'ajo', 'puerro', 'esparrago', 'alcachofa', 'brócoli', 'coliflor', 'maíz',
    'trigo', 'avena', 'cebada', 'arroz', 'lenteja', 'garbanzo', 'frijol', 'soja', 'guisante', 'haba',
    'cacahuete', 'sésamo', 'girasol', 'amapola', 'rosa', 'lirio', 'tulipán', 'margarita', 'clavel',
    'orquídea', 'jazmín', 'azucena', 'narciso', 'violeta', 'lavanda', 'romero', 'tomillo', 'albahaca',
    'perejil', 'cilantro', 'menta', 'orégano', 'laurel', 'salvia', 'estragón', 'eneldo', 'comino',
    'canela', 'clavo', 'jengibre', 'cúrcuma', 'azafrán', 'pimienta', 'vainilla', 'cardamomo', 'anís',
    'hinojo', 'mostaza', 'sabor', 'aroma', 'cocina', 'receta', 'ingrediente', 'plato', 'comida'
]

def generar_palabras():
    # Filtrar palabras de 4 a 8 caracteres, eliminar duplicados y normalizar (sin tildes para simplificar)
    palabras = set(palabra.lower() for palabra in PALABRAS_BASE if 4 <= len(palabra) <= 8)
    print(f"Palabras reales filtradas: {len(palabras)}")
    return list(palabras)

def llenar_shelf():
    palabras = generar_palabras()
    try:
        with shelve.open('palabras_shelf') as db:
            db['palabras'] = palabras
        print(f"Insertadas {len(palabras)} palabras en el archivo shelf.")
    except Exception as e:
        print(f"Error al crear el archivo shelf: {e}")

if __name__ == "__main__":
    llenar_shelf()